# frozen_string_literal: true

# Generated by `bin/rails generate current_scope:identity` (#158).
#
# This object is config.subject_identity, not config.subject_label.
# Label is display-only and fail-soft. Identity is load-bearing: a
# duplicate natural key raises, and resolve never inserts a subject.
#
# Fill identify/resolve for a key split across tables (users joined to
# contacts). For a single column, prefer `config.subject_identity = :email`
# instead of this class.
#
# Placeholder rows created by current_scope:identity:setup PLACEHOLDER=1 WRITE=1
# must be stamped with CurrentScope::SubjectIdentity::PLACEHOLDER_MARK
# ("current_scope_placeholder") so you can find and delete them.
# Production never creates one.
class CurrentScopeSubjectIdentity
  # Raise rather than return a blank key. resolve treats a blank key as no key
  # at all and returns nil, so a blank email here would mint an identity that
  # can never find this subject again — and an export would carry it forward
  # silently. This mirrors what the built-in column identities do.
  def identify(subject)
    email = subject.email
    if CurrentScope::SubjectIdentity.blank_value?(email)
      raise CurrentScope::ConfigurationError,
            "#{subject.class}##{subject.id} has a blank email, which is its " \
            "portable identity. Fill it, or identify by a column that is always present."
    end

    email
  end

  def resolve(key)
    return if key.blank?

    rows = User.where(email: key).limit(2).to_a
    case rows.size
    when 0 then nil
    when 1 then rows.first
    else
      raise CurrentScope::ConfigurationError,
            "subject_identity matched more than one User for #{key.inspect}"
    end
  end

  # Runs on every boot, and the cost is yours: the engine short-circuits its
  # own Symbol / Array identities from a unique index, but this is host code.
  # The first line does that here — delete it if no single index proves your
  # key (a key split across tables), and lean on identity:check in CI instead.
  #
  # The blank test is Ruby's, not SQL's, so it agrees with resolve exactly.
  # resolve returns nil for key.blank?, so two users whose emails are both
  # whitespace are not a collision — neither can ever be resolved. Doing it
  # in SQL would not match: TRIM() removes spaces only, while blank? also
  # covers tabs and newlines, and the answer would differ per adapter.
  # No table prefix either, so this keeps working if User maps to a table
  # that is not named "users".
  def unique?
    return true if User.connection.indexes(User.table_name)
                       .any? { |i| i.unique && i.where.nil? && i.columns == [ "email" ] }

    User.where.not(email: nil)
        .group(:email).having("COUNT(*) > 1")
        .pluck(:email).none?(&:present?)
  end

  def create_placeholder!(key)
    User.create!(
      email: key,
      name: "#{CurrentScope::SubjectIdentity::PLACEHOLDER_MARK} #{key}"
    )
  end
end
