# frozen_string_literal: true

# Generated by `bin/rails generate current_scope:identity` (#158).
#
# This object is config.subject_identity, not config.subject_label.
# Label is display-only and fail-soft. Identity is load-bearing: a
# duplicate natural key raises, and resolve never inserts a subject.
#
# Fill identify/resolve for a key split across tables (users joined to
# contacts). For a single column, prefer `config.subject_identity = :email`
# instead of this class.
#
# Placeholder rows created by current_scope:identity:setup PLACEHOLDER=1 WRITE=1
# must be stamped with CurrentScope::SubjectIdentity::PLACEHOLDER_MARK
# ("current_scope_placeholder") so you can find and delete them.
# Production never creates one.
class CurrentScopeSubjectIdentity
  def identify(subject)
    subject.email
  end

  def resolve(key)
    return if key.blank?

    rows = User.where(email: key).limit(2).to_a
    case rows.size
    when 0 then nil
    when 1 then rows.first
    else
      raise CurrentScope::ConfigurationError,
            "subject_identity matched more than one User for #{key.inspect}"
    end
  end

  # THIS RUNS ON EVERY BOOT, and it is yours to make cheap. CurrentScope
  # cannot do it for you: the engine short-circuits its own Symbol / Array
  # identities when a plain unique index covers exactly those columns, but an
  # identity OBJECT is host code, so boot pays whatever this method costs.
  #
  # If a unique index already proves this, say so and return before querying:
  #
  #   def unique?
  #     return true if User.connection.indexes(User.table_name)
  #                        .any? { |i| i.unique && i.where.nil? && i.columns == [ "email" ] }
  #     ...
  #   end
  #
  # For a key split across tables, where no single index proves it, keep the
  # query and run bin/rails current_scope:identity:check in CI instead of
  # relying on the boot check to be fast.
  #
  # The blank test is Ruby's, not SQL's, so it agrees with resolve exactly.
  # resolve returns nil for key.blank?, so two users whose emails are both
  # whitespace are not a collision — neither can ever be resolved. Doing it
  # in SQL would not match: TRIM() removes spaces only, while blank? also
  # covers tabs and newlines, and the answer would differ per adapter.
  # No table prefix either, so this keeps working if User maps to a table
  # that is not named "users".
  def unique?
    User.where.not(email: nil)
        .group(:email).having("COUNT(*) > 1")
        .pluck(:email).none?(&:present?)
  end

  def create_placeholder!(key)
    User.create!(
      email: key,
      name: "#{CurrentScope::SubjectIdentity::PLACEHOLDER_MARK} #{key}"
    )
  end
end
